# Generated by Django 4.2.6 on 2023-11-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0003_remove_coursesection_episode_coursesection_episodes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="comments",
            field=models.ManyToManyField(blank=True, to="courses.comment"),
        ),
    ]
