# Generated by Django 4.2.6 on 2023-11-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='sector_image',
        ),
    ]
