# Generated by Django 4.2.6 on 2023-11-28 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Cart',
        ),
    ]
