# Generated by Django 4.2.6 on 2023-11-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
    ]
