# Generated by Django 4.2.6 on 2023-11-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_cart_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.AddField(
            model_name='cart',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
