# Generated by Django 4.2.6 on 2023-11-28 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_cart_price_remove_cart_title_cart_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='courses',
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
