# Generated by Django 4.2.6 on 2023-11-30 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_cart_courses_cart_name_cart_price_cart_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='course_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='sector_image/'),
            preserve_default=False,
        ),
    ]
