# Generated by Django 4.2.6 on 2023-12-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_cart_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image_url',
        ),
    ]
