# Generated by Django 4.2.6 on 2023-12-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_cart_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
    ]
