# Generated by Django 4.2.6 on 2023-12-03 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image_url',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='course_images/'),
            preserve_default=False,
        ),
    ]
