# Generated by Django 4.2.6 on 2023-12-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_cart_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='image_url',
            new_name='cart_image_url',
        ),
    ]
