# Generated by Django 4.2.6 on 2023-12-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_rename_image_url_cart_cart_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_image_url',
        ),
    ]
