# Generated by Django 4.2.6 on 2023-12-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_cart_creater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='creater',
            new_name='author',
        ),
    ]
